### PR TITLE
chore(reame): add content to `readme.md`

### LINKED ISSUE #98: Add README
In order for people to help fix problems with the site, it would be really useful to have a short README file that explains how to run Hugo to generate the site.

### PR DESCRIPTION
**Pull request by baimamboukar**
This pull request closes #98 by introducing several improvements to the project's README.md file

- Add banner for the weekly challenge repo
- Add Technologies badges
- Add few features
- Add `Get Started` basic instructions
- Add `Contributing` and `License` sections
- Add join `slack` channel action

### CODE REVIEW

**Comment by manwar** [comment]
@baimamboukar Thanks for the contributions. 
I noticed the Slack join link points to Open Food Facts?

**Comment by baimamboukar** [comment]
> @baimamboukar Thanks for the contributions. I noticed the Slack join link points to Open Food Facts?

Hello @manwar 
Sorry It was a mistake... I copied it from the Outreachy page.

I just tried the second slack channel link.
It seems to be expired already
image

Can you have a look at it ?

**Comment by manwar** [comment]
@baimamboukar 
Please try this:

https://join.slack.com/share/enQtNjc1MzQ1OTU1Mjc3NS1iMDFmMzNjMDFkN2U4Y2MwY2E1MWU4M2U1YmYxNWFjNmRiMDI4MDZjNTJjYWIwYmY0MDIxMTc4OWMyNWU0ZGI1

**Comment by baimamboukar** [comment]
Hello @manwar 
It is done, I updated the `slack` invitation link

### Thanks for reviewing it ✨

**Comment by manwar** [comment]
Well done and congratulation on successful first pull request. @baimamboukar 

Do you mind take a look at the new issues I created for Outreachy?

**Comment by baimamboukar** [comment]
Thanks @manwar  ✨
Sure, I'm on it.
Thanks for creating these issues 🤲🏾

**Pull request merged**
